## Numpy 

In [1]:
#importing libraries
import numpy as np

Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. Expected Output: [[ 2 3 4] [ 5 6 7] [ 8 9 10]]

In [2]:
#Create 1D array
val = np.arange(2,11)
val

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#customize the shape
val_shp = val.reshape(3,3)
val_shp

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [4]:
# change to a matrix
val_mat = np.matrix(val_shp)
type(val_mat)

numpy.matrix

Write a NumPy program to create a null vector of size 10 and update the sixth value to 11. [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Update sixth value to 11 [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [5]:
#Create null array
az = np.zeros(10)
print("Null vetor:",az)

#Change the 6th value
az[5] = 11
print("Updated vetor:",az)

Null vetor: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated vetor: [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


Write a NumPy program to create an array with values ranging from 12 to 38. Expected Output: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

In [6]:
#Creating a 1D array
ad = np.arange(12,38)
ad

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])


Write a NumPy program to reverse an array (the first element becomes the last). Original array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37] Reverse array: [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [7]:
#Calling ad to reverse
da = ad[:: -1]
da

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

Write a NumPy program to convert an array to a floating type. Sample output: Original array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]

In [8]:
#Create 1D array
b = np.arange(1,5)
print("Array" ,b)

#Change to float type
b_flt = b.astype(float)
print("Float as", b_flt)

Array [1 2 3 4]
Float as [1. 2. 3. 4.]


Write a NumPy program to create a 2D array with 1 on the border and 0 inside. Expected Output: Original array: [[ 1. 1. 1. 1. 1.] ................... [ 1. 1. 1. 1. 1.]]

In [9]:
#5x5 matrix of zeros, double brackets as zero takes one argument
arr = np.zeros((5,5))

# Set the border elements to 1
arr[0, :] = 1  # First row
arr[-1, :] = 1  # Last row
arr[:, 0] = 1  # First column
arr[:, -1] = 1  # Last column

# Print the original array
print("Updated array:")
print(arr)

Updated array:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Write a NumPy program to find the number of elements in an array. It also finds the length of one array element in bytes and the total bytes consumed by the elements. Expected Output: Size of the array: 3 Length of one array element in bytes: 8 Total bytes consumed by the elements of the array: 24

In [10]:
# Create a 1D array with type int
c = np.arange(1,4)
c_arr = c.astype(int)
type(c_arr)

# Find the size of the array (number of elements)
size_of_array = c_arr.size

# Find the length of one array element in bytes
element_size_in_bytes = c_arr.itemsize

# Find the total bytes consumed by the elements of the array
total_bytes_consumed = size_of_array * element_size_in_bytes

# Print the results
print("Size of the array:", size_of_array)
print("Length of one array element in bytes:", element_size_in_bytes)
print("Total bytes consumed by the elements of the array:", total_bytes_consumed)

Size of the array: 3
Length of one array element in bytes: 4
Total bytes consumed by the elements of the array: 12
